##########################################################################
# Title:         Cloudbox: UnionFS | Variable Tasks                      #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# UnionFS Mount Types
################################

- name: Variables | Reset 'mount_type' variable
  set_fact:
    mount_type:

- name: Variables | Set 'mergerfs' mount variables
  set_fact:
    mount_type: "mergerfs"
  when: (mounts.unionfs | lower == "mergerfs")

- name: Variables | Set 'unionfs' mount variables
  set_fact:
    mount_type: "unionfs"
  when: (mounts.unionfs | lower == "unionfs")

- name: Variables | Set 'mount_type_is_defined' variable
  set_fact:
    mount_type_is_defined:  "{{ (mount_type is defined) and
                                (mount_type is not none) and
                                (mount_type | trim | length > 0) }}"

- name: Variables | Fail when no valid remote mount type is specified.
  fail:
    msg: "'{{ mounts.unionfs }}' is not a valid unionfs mount type."
  when: not mount_type_is_defined

################################
# Service Files List
################################

- name: Variables | Set '_service_file' variable
  set_fact:
    _service_file: "{{ mount_type }}.service"

- name: Variables | Set 'service_files_stat' variable
  stat:
    path: "/etc/systemd/system/{{ _service_file }}"
  register: service_file_stat

- name: Variables | Create empty 'service_files_temp' list
  set_fact:
    service_files_temp: []

- name: Variables | Build 'service_files' list
  set_fact:
    service_files_temp: "{{ service_files_temp + [ _service_file ] }}"
  when: service_file_stat.stat.exists

- name: Variables | Set new 'service_files' variable
  set_fact:
    service_files: "{{ service_files_temp }}"
