#########################################################################
# Title:         Cloudbox: Shell Role                                   #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set bash as default shell
  import_tasks: "bash.yml"
  when: shell|default('zsh',true) == "bash"

- name: Set zsh as default shell
  import_tasks: "zsh.yml"
  when: shell|default('zsh',true) == "zsh"
