#########################################################################
# Title:         Shell: Preinstall Task                                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Display message when kernel has been updated"
  debug:
    msg: "Kernel was updated. You will need to restart the server for changes to take effect."
  when: (preinstall_kernel_restart)

- name: "Display message when cloudbox folder location has been migrated"
  debug:
    msg: "Cloudbox folder was migrated to a new home location. Please re-login with the '{{user}}' account and run the Cloudbox installer from the '{{cloudbox_folder_path}}/' path."
  when: (preinstall_user_relogin)

- name: "Cloudbox pre-install has completed!"
  debug:
    msg: "Cloudbox pre-install has completed!"