#########################################################################
# Title:         Cloudbox: Nginx-Proxy | Letsencrypt | DNS Validation   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Letsencrypt | DNS Validation | Import 'domains.conf' file
  template:
    src: "dns_validation/domains.conf.j2"
    dest: "/opt/nginx-proxy/certs/letsencrypt/domains.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes

- name: Letsencrypt | DNS Validation | Create and start container
  docker_container:
    name: letsencrypt
    image: "adferrand/letsencrypt-dns"
    pull: yes
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - "/opt/nginx-proxy/certs/letsencrypt:/etc/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      CERTS_USER_OWNER: "{{ user.name }}"
      CERTS_GROUP_OWNER: "{{ user.name }}"
      CERTS_FILES_MODE: "0664"
      CERTS_DIRS_MODE: "0775"
      LETSENCRYPT_USER_MAIL: "{{ user.email }}"
      LEXICON_PROVIDER: "cloudflare"
      LEXICON_CLOUDFLARE_USERNAME: "{{ cloudflare.email }}"
      LEXICON_CLOUDFLARE_TOKEN: "{{ cloudflare.api }}"
      TZ: "{{ tz }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks_cli_compatible: yes
    networks:
      - name: cloudbox
        aliases:
          - letsencrypt
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
