#########################################################################
# Title:         Cloudbox: Nvidia | Docker Tasks                        #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Docker | Add 'nvidia-container-runtime' repo key
  apt_key:
    url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    state: present

- name: Docker | Add 'nvidia-container-runtime' APT list
  apt_repository:
    repo: "{{ item }}"
    filename: nvidia-container-runtime.list
    state: present
    mode: 0644
    update_cache: yes
  with_items:
    - 'deb https://nvidia.github.io/libnvidia-container/{{ ansible_distribution|lower }}{{ ansible_distribution_version }}/$(ARCH) /'
    - 'deb https://nvidia.github.io/nvidia-container-runtime/{{ ansible_distribution|lower }}{{ ansible_distribution_version }}/$(ARCH) /'

- name: Docker | Install 'nvidia-container-runtime'
  apt:
    name: nvidia-container-runtime
    update_cache: yes
    state: present

- name: Docker | Populate Service Facts
  service_facts:

- name: Docker | Get Docker service state
  set_fact:
    docker_service_running: "{{ (services['docker.service'] is defined) and (services['docker.service']['state'] == 'running') }}"

- name: Docker | Gather list of running Docker containers
  shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' | xargs echo -n"
  register: docker_running_containers
  ignore_errors: yes
  when: (docker_service_running)

- name: Docker | Stop all running Docker containers
  shell: "docker stop {{ docker_running_containers.stdout }}"
  ignore_errors: yes
  when: (docker_service_running) and not (docker_running_containers.stdout | trim | length == 0)

- name: Docker | Stop docker service
  systemd:
    name: docker
    state: stopped
  when: (docker_service_running)

# https://github.com/linkernetworks/vortex-installer/blob/master/roles/common/tasks/nvidia-docker.yml
- name: Docker | Add runtime to '/etc/docker/daemon.json'
  shell: |
    jq '."default-runtime" = "nvidia"
        | .runtimes.nvidia.path = "/usr/bin/nvidia-container-runtime"
        | .runtimes.nvidia.runtimeArgs = []' \
    /etc/docker/daemon.json | jq . | sponge /etc/docker/daemon.json

- name: Docker | Start docker service
  systemd:
    name: docker
    state: started
  when: (docker_service_running)

- name: Docker | Re-start all previously running Docker containers
  shell: 'docker start {{ docker_running_containers.stdout }}'
  ignore_errors: yes
  when: (docker_service_running) and not (docker_running_containers.stdout | trim | length == 0)
