#########################################################################
# Title:         Cloudbox: Rclone Role                                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Build URL Tasks
  import_tasks: "subtasks/01_build_url.yml"

- name: Install Binary Tasks
  import_tasks: "subtasks/02_install_binary.yml"

- name: Import Existing Config Tasks
  import_tasks: "subtasks/03_import_config.yml"

- name: Preinstall Tasks
  include_tasks: "subtasks/99_preinstall.yml"
  when: ('preinstall' in ansible_run_tags)
