#########################################################################
# Title:         Cloudbox: Radarr Role                                  #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  docker_container:
    name: "{{ lookup('vars', role_name + '_docker_container') }}"
    state: absent

- name: Hotio Migration Tasks
  include_tasks: "{{ resources_tasks_path }}/hotio/migrator/main.yml"

- name: Create directories
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Darkerr Tasks
  import_tasks: "subtasks/darkerr.yml"

- name: Import '99-cont-init-script-runner.sh' script
  copy:
    src: "{{ resources_tasks_path }}/hotio/cont-init.d/files/99-cont-init-script-runner.sh"
    dest: "{{ lookup('vars', role_name + '_paths_location') }}/99-cont-init-script-runner.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes

- name: SMA Tasks
  include_tasks: "{{ resources_tasks_path }}/hotio/sickbeard_mp4_automator/install_reqs.yml"

- name: Docker Devices Task
  include_tasks: "{{ resources_tasks_path }}/docker/set_docker_devices_variable.yml"
  when:
    - (gpu.intel or gpu.nvidia.enabled)
    - (use_sma)

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Install Tasks
  import_tasks: "subtasks/post-install/main.yml"
