#########################################################################
# Title:         Cloudbox: System | Time Zone Tasks                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Time Zone | Remove '/etc/localtime'
  file:
    path: "/etc/localtime"
    state: absent

- name: Time Zone | Install tzdata
  apt:
    name: tzdata
    state: present

- name: Time Zone | Fetch Time Zone if set to 'auto'
  block:

  - name: Time Zone | Get Time Zone from 'http://ip-api.com'
    uri:
      url: http://ip-api.com/line?fields=timezone
      return_content: yes
    register: ip_api_timezone_response

  - name: Time Zone | Set 'tz' variable from 'http://ip-api.com'
    set_fact:
      tz: "{{ ip_api_timezone_response.content | trim }}"
    when:
      - (ip_api_timezone_response is succeeded)
      - (ip_api_timezone_response.content | trim | length > 0)

  when:
    - (system is defined)
    - (system.timezone is defined)
    - ('auto' in system.timezone | lower)
  ignore_errors: yes

- name: Time Zone | Set Time Zone
  timezone:
    name: "{{ tz }}"
  notify: Handers | Update 'tzdata'

- name: Time Zone | Import '/etc/timezone'
  template:
    src: "etc/timezone.j2"
    dest: "/etc/timezone"
    mode: 0644
    force: yes
  notify: Handers | Update 'tzdata'
