#########################################################################
# Title:         Cloudbox: Kernel Role                                  #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Variables Task
  include_tasks: "subtasks/00_variables.yml"

- name: Preinstall Task
  include_tasks: "subtasks/01_preinstall.yml"
  when: ('preinstall' in ansible_run_tags)

- name: Cron Tasks
  include_tasks: "subtasks/02_cron.yml"

# Ubuntu Mainline Kernel Updater Script
- name: Script Tasks
  include_tasks: "subtasks/03_script.yml"
  when: (ansible_distribution == 'Ubuntu')

# Ubuntu 16.04 HWE Update
- name: Update Tasks
  include_tasks: "subtasks/04_update.yml"
  when:
    - (ansible_distribution == 'Ubuntu')
    - (ansible_distribution_version is version('16.04', '=='))
    - (ansible_kernel is version('4.10', '<'))

- name: Restart Tasks
  include_tasks: "subtasks/05_restart.yml"
  when:
    - (reboot_is_necessary)
    - (not continuous_integration)

- name: Checks Task
  include_tasks: "subtasks/06_checks.yml"
