#####################################################################################
# Title:         Cloudbox: Resources | Tasks | systemd | Update Service Credentials #
# Author(s):     desimaniac                                                         #
# URL:           https://github.com/cloudbox/cloudbox                               #
# --                                                                                #
#         Part of the Cloudbox project: https://cloudbox.works                      #
#####################################################################################
#                   GNU General Public License v3.0                                 #
#####################################################################################
---
- name: Resources | Tasks | systemd | Update Service Credentials | set '_service_file' variable
  set_fact:
    _service_file: "{{ _service_name }}.service"

- name: Resources | Tasks | systemd | Update Service Credentials | set '_service_path' variable
  set_fact:
    _service_path: "/etc/systemd/system/{{ _service_file }}"

- name: Resources | Tasks | systemd | Update Service Credentials | check if '{{ _service_file }}' exists
  stat:
    path: "{{ _service_path }}"
  register: service_status

- name: Resources | Tasks | systemd | Update Service Credentials | existing '{{ _service_file }}' tasks
  block:

  - name: Resources | Tasks | systemd | Update Service Credentials | update credentials in '{{ _service_file }}'
    ini_file:
      path: "{{ _service_path }}"
      section: Service
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      state: present
      no_extra_spaces: yes
    loop:
      - { option: 'User', value: "{{ user.name }}" }
      - { option: 'Group', value: "{{ user.name }}" }
    register: credentials_state

  - name: Resources | Tasks | systemd | Update Service Credentials | systemd daemon-reload
    systemd: daemon_reload=yes
    when: credentials_state is changed

  when: service_status.stat.exists
