##########################################################################
# Title:         Cloudbox: Plex | Claim Server                           #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Claim Server | Get {{ plex_name | title }} claim code via API
  block:

  - name: "Get {{ plex_name | title }} claim code"
    uri:
      url: https://plex.tv/api/claim/token.json
      user: "{{ plex.user }}"
      password: "{{ plex.pass }}"
      force_basic_auth: yes
    register: plex_claim

  - name: "Claim Server | Set 'plex_claim_code' variable"
    set_fact:
      plex_claim_code: "{{ plex_claim.json.token }}"

  when: (plex_account_is_enabled)

- name: Claim Server | Get {{ plex_name | title }} claim code via prompts
  block:

  - name: "Claim Server | Ask user for {{ plex_name | title }} claim code"
    pause:
      prompt: "Please visit 'https://plex.tv/claim', login with your Plex account,
        copy the 'Claim Code', paste it below, and press ENTER."
    register: plex_claim_code_prompt

  - name: "Claim Server | Set 'plex_claim_code' variable"
    set_fact:
      plex_claim_code: "{{ plex_claim_code_prompt.user_input }}"

  when: (not plex_account_is_enabled)

- name: Claim Server | Assert {{ plex_name | title }} claim code exists
  assert:
    that:
      - "plex_claim_code is defined"
      - "plex_claim_code is not none"
      - "plex_claim_code | trim | length > 0"
    quiet: yes

- name: "Claim Server | Display {{ plex_name | title }} claim code"
  debug:
    msg: "Using Plex Claim Code{{ ':' }} {{ plex_claim_code }}"
