#########################################################################
# Title:         Cloudbox: Docker | Binary Tasks 2                      #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Release '{{ vars[item ~ '_dpkg'] }}' from hold
  dpkg_selections:
    name: "{{ vars[item ~ '_dpkg'] }}"
    selection: install

- name: Binary | Install '{{ lookup('vars', item + '_package') }}'
  apt:
    name: "{{ lookup('vars', item + '_package') }}"
    state: "{{ docker_package_state }}"
    update_cache: yes
    force: yes

- name: Binary | Put '{{ vars[item ~ '_dpkg'] }}' into hold
  dpkg_selections:
    name: "{{ vars[item ~ '_dpkg'] }}"
    selection: hold
  when: put_docker_dpkg_into_hold

- name: Binary | Get '{{ vars[item ~ '_name'] }}' version
  shell: "{{ vars[item ~ '_filepath'] }} --version | head -n 1 | awk '{ print $3 }' | sed 's/,$//'"
  register: binary_version
  ignore_errors: yes
  changed_when: false

- name: Binary | Display '{{ vars[item ~ '_name'] }}' version
  debug:
    msg: "{{ vars[item ~ '_name'] }} version {{ binary_version.stdout }} installed."
  when: binary_version is defined
