##########################################################################
# Title:         Cloudbox: Organizr | Default Variables                  #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

organizr_name: organizr

################################
# Paths
################################

organizr_paths_folder: "{{ organizr_name }}"
organizr_paths_location: "{{ server_appdata_path }}/{{ organizr_paths_folder }}"
organizr_paths_folders_list:
  - "{{ organizr_paths_location }}"

################################
# Web
################################

organizr_web_subdomain: "{{ 'organizr'
                            if (not (organizr.direct_domain | default(false,true)))
                            else 'www' }}"
organizr_web_domain: "{{ user.domain }}"
organizr_web_port: "80"
organizr_web_url: "{{ 'https://' + organizr_web_subdomain + '.' + organizr_web_domain
                      if (reverse_proxy_is_enabled
                      else 'http://localhost:' + organizr_web_port }}"

################################
# DNS
################################

organizr_dns_record: "{{ organizr_web_subdomain
                          if (not (organizr.direct_domain | default(false,true)))
                          else ['www',organizr_web_domain] }}"

organizr_dns_zone: "{{ organizr_web_domain }}"

################################
# Reverse Proxy
################################

organizr_reverse_proxy_virtual_host: "{{ (organizr_web_subdomain
                                              + '.'
                                              + organizr_web_domain)
                                          if (not (organizr.direct_domain | default(false,true)))
                                          else (organizr_web_subdomain
                                              + '.'
                                              + organizr_web_domain
                                              + ','
                                              + organizr_web_domain) }}"

organizr_reverse_proxy_virtual_port: "{{ organizr_web_port }}"

organizr_reverse_proxy_letsencrypt_host: "{{ (organizr_web_subdomain
                                                  + '.'
                                                  + organizr_web_domain)
                                              if (not (organizr.direct_domain | default(false,true)))
                                              else (organizr_web_subdomain
                                                  + '.'
                                                  + organizr_web_domain
                                                  + ','
                                                  + organizr_web_domain) }}"

organizr_reverse_proxy_letsencrypt_email: "{{ user.email }}"

################################
# Docker
################################

# Container
organizr_docker_container: "{{ organizr_name }}"

# Image
organizr_docker_image_pull: yes
organizr_docker_image_tag: "plex"
organizr_docker_image: "organizrtools/organizr-v2:{{ organizr_docker_image_tag }}"

# Ports
organizr_docker_ports_defaults:
  - "{{ organizr_web_port }}"
organizr_docker_ports_custom: []
organizr_docker_ports: "{{ organizr_docker_ports_defaults
                              + organizr_docker_ports_custom
                          if (not reverse_proxy_is_enabled)
                          else [] + organizr_docker_ports_custom }}"

# Envs
organizr_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
organizr_docker_envs_custom: {}
organizr_docker_envs_reverse_proxy: {}
organizr_docker_envs: "{{ organizr_docker_envs_default
                              | combine(organizr_docker_envs_custom)
                              | combine(organizr_docker_envs_reverse_proxy)
                              | combine(docker_envs_reverse_proxy_common)
                          if (reverse_proxy_is_enabled)
                          else organizr_docker_envs_default
                              | combine(organizr_docker_envs_custom) }}"

# Volumes
organizr_docker_volumes_default:
  - "{{ organizr_paths_location }}:/config"
organizr_docker_volumes_custom: []
organizr_docker_volumes: "{{ organizr_docker_volumes_default
                                  + organizr_docker_volumes_custom
                                  + docker_volumes_downloads_common }}"

# Devices
organizr_docker_devices_default: []
organizr_docker_devices_custom: []
organizr_docker_devices: "{{ organizr_docker_devices_default
                                  + organizr_docker_devices_custom }}"

# Hosts
organizr_docker_hosts_default: []
organizr_docker_hosts_custom: []
organizr_docker_hosts: "{{ docker_hosts_common
                                | combine(organizr_docker_hosts_default)
                                | combine(organizr_docker_hosts_custom) }}"

# Labels
organizr_docker_labels_default: {}
organizr_docker_labels_custom: {}
organizr_docker_labels: "{{ docker_labels_common
                                | combine(organizr_docker_labels_default)
                                | combine(organizr_docker_labels_custom) }}"

# Hostname
organizr_docker_hostname: "{{ organizr_name }}"

# Networks
organizr_docker_networks_alias: "{{ organizr_name }}"
organizr_docker_networks_default: []
organizr_docker_networks_custom: []
organizr_docker_networks: "{{ docker_networks_common
                                  + organizr_docker_networks_default
                                  + organizr_docker_networks_custom }}"

# Capabilities
organizr_docker_capabilities_default: []
organizr_docker_capabilities_custom: []
organizr_docker_capabilities: "{{ organizr_docker_capabilities_default
                                      + organizr_docker_capabilities_custom }}"

# Security Opts
organizr_docker_security_opts_default: []
organizr_docker_security_opts_custom: []
organizr_docker_security_opts: "{{ organizr_docker_security_opts_default
                                      + organizr_docker_security_opts_custom }}"

# Restart Policy
organizr_docker_restart_policy: unless-stopped

# State
organizr_docker_state: started
