#########################################################################
# Title:         Cloudbox: Remote | Mount Path Tasks                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Mount Path | Force unmount '{{ mount_path }}'"
  shell: "/bin/umount -f '{{ mount_path }}' 2>/dev/null || :"
  ignore_errors: yes

- name: "Mount Path | Check if '{{ mount_path }}' exists"
  stat:
    path: "{{ mount_path }}"
  register: mount_path_stat
  ignore_errors: yes

- name: "Mount Path | Tasks for '{{ mount_path }}' path"
  block:

  - name: "Mount Path | Remove empty directories in '{{ mount_path }}'"
    shell: "find '{{ mount_path }}' -type d -empty -delete"
    ignore_errors: yes

  - name: "Mount Path | Recursively find '{{ mount_path }}' files"
    find:
      paths: '{{ mount_path }}'
      hidden: yes
      recurse: yes
    register: mount_path_stat_files

  - name: "Mount Path | Backup non-empty '{{ mount_path }}' path"
    shell: "mv {{ mount_path }} {{ mount_path }}_{{ '%Y-%m-%d_%H.%M.%S' | strftime(ansible_date_time['epoch']|int) }}"
    ignore_errors: yes
    when: (mount_path_stat_files.matched|int > 0)

  - name: "Mount Path | Remove '{{ mount_path }}'"
    file:
      path: "{{ mount_path }}"
      state: absent

  when: (mount_path_stat is failed) or (mount_path_stat.stat.exists)
