#########################################################################
# Title:         Cloudbox: DNS Role                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: DNS Tasks
  include_tasks: "main2.yml"
  vars:
    dns_record: "{{ item }}"
    dns_zone: "{{ _dns_role_zone }}"
    dns_action: "{{ _dns_role_action }}"
  loop: "{{ _dns_role_record }}"
  when: reverse_proxy_is_enabled
