#########################################################################
# Title:         Cloudbox: DNS Role                                     #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: DNS Tasks
  include_tasks: "main2.yml"
  when: reverse_proxy_is_enabled
