#########################################################################
# Title:         Cloudbox: Kernel | Update Tasks                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Update | Update linux kernel
  apt:
    name: "{{ kernel_update_apt_package }}"
    update_cache: yes
    state: latest
  register: r

- name: Update | Fix broken APT install
  shell: "{{ kernel_update_apt_fix }}"
  when: (r.changed)

- name: Update | Set 'reboot_is_necessary' variable
  set_fact:
    reboot_is_necessary: true
  when: (r.changed)

- name: Update | Kernel was updated
  debug:
    msg: "Kernel was updated."
  when: (r.changed)

- name: Update | Kernel was not updated
  debug:
    msg: "Kernel was not updated."
  when: (not r.changed)
