#########################################################################
# Title:         Cloudbox: Ombi Role                                    #
# Author(s):     RXWatcher1, l3uddz, desimaniac                         #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/ombi                                             #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: "{{ ombi.subdomain|default('ombi',true) }}"

- name: Stop and remove any existing container
  docker_container:
    name: ombi
    state: absent

# START - Suitarr Migration Tasks
- name: Check folder exists
  stat:
    path: /opt/ombi
  register: folder

- name: Check subfolder exists
  stat:
    path: /opt/ombi/app
  register: subfolder

- name: Move 'ombi' folder contents to 'app' subfolder
  shell: |
    mv /opt/ombi /tmp/app
    mkdir /opt/ombi
    mv /tmp/app /opt/ombi/
    find /opt/ombi/* -type d -empty -delete
    chown -R {{user}}:{{user}} /opt/ombi
  when: (folder.stat.exists) and not (subfolder.stat.exists)
# END - Suitarr Migration Tasks

- name: Create ombi directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/ombi

- name: Create and start container
  docker_container:
    name: ombi
    image: "hotio/ombi"
    pull: yes
    env:
      VERSION: "{{suitarr.version}}"
      FALLBACK: "yes"
      BACKUP: "no"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      UMASK: 002
      VIRTUAL_HOST: "{{ ombi.subdomain|default('ombi',true) }}.{{domain}}"
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: "{{ ombi.subdomain|default('ombi',true) }}.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/ombi:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - ombi
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
