########################################################################################
# Title:         Cloudbox: Settings | Migrator | 'ansible.cfg' | Migration 01          #
# Author(s):     desimaniac                                                            #
# URL:           https://github.com/cloudbox/cloudbox                                  #
# --                                                                                   #
#                 Part of the Cloudbox project: https://cloudbox.works                 #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################
---
- name: "Migrator | 'ansible.cfg' | Add default entries to 'ansible.cfg'"
  ini_file:
    path: "{{ playbook_dir }}/{{ file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
    no_extra_spaces: no
    owner: "{{ cloudbox_yml.stat.uid }}"
    group: "{{ cloudbox_yml.stat.gid }}"
    mode: 0664
  register: ansible_cfg_update_status
  loop:
    - { section: 'defaults', option: 'roles_path', value: 'roles:resources/roles' }
    - { section: 'defaults', option: 'hash_behaviour', value: 'merge' }
    - { section: 'defaults', option: 'fact_path', value: './ansible_facts.d' }
    - { section: 'defaults', option: 'log_path', value: './cloudbox.log' }

- name: "Migrator | 'ansible.cfg' | Build 'files_updated_successfully' list"
  set_fact:
    files_updated_successfully: "{{ files_updated_successfully }} + [ '{{ file }}' ]"
    exit_is_necessary: true
  when: item.changed
  loop: "{{ ansible_cfg_update_status.results }}"
