#########################################################################
# Title:         Cloudbox: Settings | Finish                            #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Finish | Check 'settings-updater.py' for new settings"
  debug:
    msg:
      - "The 'settings_updater.py' script updated the following
          file{{ files_updated_successfully | pluralize }}: '{{ files_updated_successfully | difference(['ansible.cfg']) | join(', ') | trim }}'"
      - "Please check {{ files_updated_successfully | pluralize('this file','these files') }} for the newly added settings"
      - "You can also review the log file: 'settings-updater.log'"
  when:
    - files_updated_successfully | difference(['ansible.cfg']) | length > 0

# Exit playbook When necessary
- name: Finish | Exit Tasks
  block:

  - name: "Finish | Check 'settings-updater.py' run status for errors"
    debug:
      msg:
        - "The 'settings_updater.py' script exited with an error when updating the following
            file{{ files_updated_unsuccessfully | pluralize }}: '{{ files_updated_unsuccessfully | join(', ') | trim }}'"
        - "Please check 'settings-updater.log' for details"
    when: files_updated_unsuccessfully | length > 0

  - name: "Finish | 'ansible.cfg' was updated."
    debug:
      msg:
        - "Settings Role updated 'ansible.cfg'"
        - "You will need to re-run your previous tag."
    when: ('ansible.cfg' in files_updated_successfully)

  - name: "Finish | Exit so that user can check updated config files"
    debug:
      msg: "Cloudbox Installer will now exit."

  - name: "Finish | Exit"
    meta: end_play

  when: exit_is_necessary

# Make sure accounts.yml has been filled in by user
- name: "Finish | Get stats on 'accounts.yml' for hash check"
  stat:
    path: "{{ playbook_dir }}/accounts.yml"
  register: accounts_yml

- name: "Finish | Get stats on 'accounts.yml.default' for hash check"
  stat:
    path: "{{ playbook_dir }}/defaults/accounts.yml.default"
  register: accounts_yml_default

# Sanity Checks
- name: "Finish | Ensure that 'accounts.yml' is configured"
  assert:
    that:
      - accounts_yml.stat.exists
      - accounts_yml.stat.checksum != accounts_yml_default.stat.checksum
      - '"{{ user.domain }}" != "testcloudbox.ml"'
    msg: "You must configure 'accounts.yml' before running the Cloudbox installer"
