#########################################################################
# Title:         Cloudbox: Cloudflare | Subdomains Task                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
## Add 'cloudbox_type' subdomain
- name: "Cloudflare | Subdomains | Add '{{ cloudbox_type }}' subdomain to '{{ user.domain }}'"
  import_tasks: "subdomains/add_subdomain.yml"

## Remove 'cloudbox' subdomain for Mediabox/Feederbox setups.
- name: "Cloudflare | Subdomains | Remove 'cloudbox' subdomain from '{{ user.domain }}'"
  import_tasks: "subdomains/remove_subdomain.yml"
  when: cloudbox_type is regex('mediabox|feederbox')
